#OBJS specifies which files to compile as part of the project
OBJS = random.cpp
PAC = Pac.cpp
Gho = Ghost.cpp
OBJ_NAME = t

all: $(OBJS)
	g++ $(OBJS) $(PAC) $(Gho) -w -lSDL2 -lSDL2_image -o $(OBJ_NAME)
